version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

      # Usuario admin automático
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "admin"
      _AIRFLOW_WWW_USER_PASSWORD: "admin"
      _AIRFLOW_WWW_USER_FIRSTNAME: "Airflow"
      _AIRFLOW_WWW_USER_LASTNAME: "Admin"
      _AIRFLOW_WWW_USER_EMAIL: "admin@example.com"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    entrypoint: >
      bash -c "
      airflow db init &&
      airflow users create \
        --username $${_AIRFLOW_WWW_USER_USERNAME} \
        --password $${_AIRFLOW_WWW_USER_PASSWORD} \
        --firstname $${_AIRFLOW_WWW_USER_FIRSTNAME} \
        --lastname $${_AIRFLOW_WWW_USER_LASTNAME} \
        --role Admin \
        --email $${_AIRFLOW_WWW_USER_EMAIL} || true &&
      airflow webserver
      "
    restart: always

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/opt/airflow/.env
    command: scheduler
    restart: always

networks:
  default:
    name: airflow_network
